# wo_cut_marginal_sig_lr_1e_4_tr_3_bz_12_seq_8
gpus: [6,7]
results_dir: './test_results/'
n_channels: 2
n_classes: 1
shuffle: True

learning_rate: 0.0001
batchsize: 6
val_batchsize: 4
seq_len: 8
bilinear: False
patience: 5

lambdaLayer: True
sigmoid: True
temporal: True
cut_marginal: False
lr_scheduler: True
val_train: True
kernel_size: 3
seed: 0
tr: 3

var_t: 6